package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jugadortorneo generated by hbm2java
 */
@Entity
@Table(name = "jugadortorneo", schema = "public")
public class Jugadortorneo implements java.io.Serializable {

	private long jugadortorneoId;
	private Jugador jugador;
	private Torneo torneo;
	private Long puntor;
	private Boolean estado;

	public Jugadortorneo() {
	}

	public Jugadortorneo(long jugadortorneoId, Torneo torneo) {
		this.jugadortorneoId = jugadortorneoId;
		this.torneo = torneo;
	}

	public Jugadortorneo(long jugadortorneoId, Jugador jugador, Torneo torneo, Long puntor, Boolean estado) {
		this.jugadortorneoId = jugadortorneoId;
		this.jugador = jugador;
		this.torneo = torneo;
		this.puntor = puntor;
		this.estado = estado;
	}

	@Id

	@Column(name = "jugadortorneo_id", unique = true, nullable = false)
	public long getJugadortorneoId() {
		return this.jugadortorneoId;
	}

	public void setJugadortorneoId(long jugadortorneoId) {
		this.jugadortorneoId = jugadortorneoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedulajugador")
	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtor", nullable = false)
	public Torneo getTorneo() {
		return this.torneo;
	}

	public void setTorneo(Torneo torneo) {
		this.torneo = torneo;
	}

	@Column(name = "puntor")
	public Long getPuntor() {
		return this.puntor;
	}

	public void setPuntor(Long puntor) {
		this.puntor = puntor;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
