package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jugadortorneo generated by hbm2java
 */
@Entity
@Table(name = "jugadortorneo", schema = "public")
public class Jugadortorneo implements java.io.Serializable {



	private long jugadortorneoId;
	private long idtorneo;
	private String cedula;
	private long puntor;
	private String estado;



	public Jugadortorneo(long jugadortorneoId, long idtorneo, String cedula, long puntor,
			String estado) {
		super();
		this.jugadortorneoId = jugadortorneoId;
		this.idtorneo = idtorneo;
		this.puntor = puntor;
		this.estado = estado;
		this.cedula = cedula;
	}



	public Jugadortorneo() {
	}



	@Id
	@Column(name = "jugadortorneo_id", unique = true, nullable = false)
	public long getJugadortorneoId() {
		return this.jugadortorneoId;
	}

	public void setJugadortorneoId(long jugadortorneoId) {
		this.jugadortorneoId = jugadortorneoId;
	}
	@Column(name = "puntor", nullable = true)
	public long getPuntor() {
		return this.puntor;
	}

	public void setPuntor(long puntor) {
		this.puntor = puntor;
	}

	@Column(name = "estado", nullable = true)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@Column(name = "idtor", nullable = false)
	public long getIdtorneo() {
		return idtorneo;
	}



	public void setIdtorneo(long idtorneo) {
		this.idtorneo = idtorneo;
	}
	
	@Column(name = "cedulajugador", nullable = true)
	public final String getCedula() {
		return cedula;
	}



	public final void setCedula(String cedula) {
		this.cedula = cedula;
	}







}
