package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", schema = "public")
public class Mensaje implements java.io.Serializable {

	private long mensajeId;
	private String contenido;
	private Character estadomsg;
	private Set<Mensajejugador> mensajejugadors = new HashSet<Mensajejugador>(0);

	public Mensaje() {
	}

	public Mensaje(long mensajeId, String contenido) {
		this.mensajeId = mensajeId;
		this.contenido = contenido;
	}

	public Mensaje(long mensajeId, String contenido, Character estadomsg, Set<Mensajejugador> mensajejugadors) {
		this.mensajeId = mensajeId;
		this.contenido = contenido;
		this.estadomsg = estadomsg;
		this.mensajejugadors = mensajejugadors;
	}

	@Id

	@Column(name = "mensaje_id", unique = true, nullable = false)
	public long getMensajeId() {
		return this.mensajeId;
	}

	public void setMensajeId(long mensajeId) {
		this.mensajeId = mensajeId;
	}

	@Column(name = "contenido", nullable = false)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Column(name = "estadomsg", length = 1)
	public Character getEstadomsg() {
		return this.estadomsg;
	}

	public void setEstadomsg(Character estadomsg) {
		this.estadomsg = estadomsg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mensaje")
	public Set<Mensajejugador> getMensajejugadors() {
		return this.mensajejugadors;
	}

	public void setMensajejugadors(Set<Mensajejugador> mensajejugadors) {
		this.mensajejugadors = mensajejugadors;
	}

}
