package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mensajejugador generated by hbm2java
 */
@Entity
@Table(name = "mensajejugador", schema = "public")
public class Mensajejugador implements java.io.Serializable {

	private long mensajejugadorId;
	private long mensaje_id;
	private String cedulades;
	private String cedularem;
	private Mensaje mensaje;
	private Persona personaByCedulades;
	private Persona personaByCedularem;
	

	public Mensajejugador() {
	}
	public Mensajejugador(long mensajejugadorId, long mensaje_id, String cedulades, String cedularem) {
		super();
		this.mensajejugadorId = mensajejugadorId;
		this.mensaje_id = mensaje_id;
		this.cedulades = cedulades;
		this.cedularem = cedularem;
	}
	@Id

	@Column(name = "mensajejugador_id", unique = true, nullable = false)
	public long getMensajejugadorId() {
		return this.mensajejugadorId;
	}

	public void setMensajejugadorId(long mensajejugadorId) {
		this.mensajejugadorId = mensajejugadorId;
	}
	@Column(name = "cedulades")
	public String getCedulades() {
		return cedulades;
	}
	public void setCedulades(String cedulades) {
		this.cedulades = cedulades;
	}
	@Column(name = "cedularem")
	public String getCedularem() {
		return cedularem;
	}
	public void setCedularem(String cedularem) {
		this.cedularem = cedularem;
	}
	@Column(name = "idmensajejugador")
	public long getIdmensaje() {
		return mensaje_id;
	}
	public void setIdmensaje(long mensaje_id) {
		this.mensaje_id = mensaje_id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmensajejugador",insertable=false,updatable=false)
	public Mensaje getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(Mensaje mensaje) {
		this.mensaje = mensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedulades", insertable=false,updatable=false)
	public Persona getPersonaByCedulades() {
		return this.personaByCedulades;
	}

	public void setPersonaByCedulades(Persona personaByCedulades) {
		this.personaByCedulades = personaByCedulades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedularem",insertable=false,updatable=false)
	public Persona getPersonaByCedularem() {
		return this.personaByCedularem;
	}
	public void setPersonaByCedularem(Persona personaByCedularem) {
		this.personaByCedularem = personaByCedularem;
	}
	
	
	
}
