package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prediccion generated by hbm2java
 */
@Entity
@Table(name = "prediccion", schema = "public")
public class Prediccion implements java.io.Serializable {

	private long prediccionId;
	private String cedulajugador;
	private long idpartido;
	private Jugador jugador;
	private Partido partido;
	private long prediccionlocal;
	private long prediccionvisitante;
	private Date fechaprediccion;
	private Boolean estado;

	public Prediccion() {
	}

	public Prediccion(long prediccionId, String cedulajugador, long idpartido, long prediccionlocal,
			long prediccionvisitante, Date fechaprediccion, Boolean estado) {
		super();
		this.prediccionId = prediccionId;
		this.cedulajugador = cedulajugador;
		this.idpartido = idpartido;
		this.prediccionlocal = prediccionlocal;
		this.prediccionvisitante = prediccionvisitante;
		this.fechaprediccion = fechaprediccion;
		this.estado = estado;
	}
	@Id

	@Column(name = "prediccion_id", unique = true, nullable = false)
	public long getPrediccionId() {
		return this.prediccionId;
	}

	public void setPrediccionId(long prediccionId) {
		this.prediccionId = prediccionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedulajugador", insertable=false,updatable=false)
	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpartido", nullable = false,insertable=false,updatable=false)
	public Partido getPartido() {
		return this.partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	@Column(name = "prediccionlocal", nullable = false)
	public long getPrediccionlocal() {
		return this.prediccionlocal;
	}

	public void setPrediccionlocal(long prediccionlocal) {
		this.prediccionlocal = prediccionlocal;
	}

	@Column(name = "prediccionvisitante", nullable = false)
	public long getPrediccionvisitante() {
		return this.prediccionvisitante;
	}

	public void setPrediccionvisitante(long prediccionvisitante) {
		this.prediccionvisitante = prediccionvisitante;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaprediccion", nullable = false, length = 29)
	public Date getFechaprediccion() {
		return this.fechaprediccion;
	}

	public void setFechaprediccion(Date fechaprediccion) {
		this.fechaprediccion = fechaprediccion;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public String getCedulajugador() {
		return cedulajugador;
	}

	public void setCedulajugador(String cedulajugador) {
		this.cedulajugador = cedulajugador;
	}

	public long getIdpartido() {
		return idpartido;
	}

	public void setIdpartido(long idpartido) {
		this.idpartido = idpartido;
	}
	
	

}
