package quinielasocial.lab.domain.entity;
// Generated 23/03/2016 01:44:51 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name = "resultado", schema = "public")
public class Resultado implements java.io.Serializable {

	private long resultadoId;
	private Partido partido;
	private long scorelocal;
	private long scorevisitante;
	private Set<Partido> partidos = new HashSet<Partido>(0);

	public Resultado() {
	}

	public Resultado(long resultadoId, Partido partido, long scorelocal, long scorevisitante) {
		this.resultadoId = resultadoId;
		this.partido = partido;
		this.scorelocal = scorelocal;
		this.scorevisitante = scorevisitante;
	}

	public Resultado(long resultadoId, Partido partido, long scorelocal, long scorevisitante, Set<Partido> partidos) {
		this.resultadoId = resultadoId;
		this.partido = partido;
		this.scorelocal = scorelocal;
		this.scorevisitante = scorevisitante;
		this.partidos = partidos;
	}

	@Id

	@Column(name = "resultado_id", unique = true, nullable = false)
	public long getResultadoId() {
		return this.resultadoId;
	}

	public void setResultadoId(long resultadoId) {
		this.resultadoId = resultadoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpartido", nullable = false)
	public Partido getPartido() {
		return this.partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	@Column(name = "scorelocal", nullable = false)
	public long getScorelocal() {
		return this.scorelocal;
	}

	public void setScorelocal(long scorelocal) {
		this.scorelocal = scorelocal;
	}

	@Column(name = "scorevisitante", nullable = false)
	public long getScorevisitante() {
		return this.scorevisitante;
	}

	public void setScorevisitante(long scorevisitante) {
		this.scorevisitante = scorevisitante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resultado")
	public Set<Partido> getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set<Partido> partidos) {
		this.partidos = partidos;
	}

}
